#!/bin/sh

if [ "$interface" != "vpn_${SE_NICNAME}" ]; then
  exit 0;
fi

if [ "$reason" = BOUND ] || [ "$reason" = RENEW ] ||
   [ "$reason" = REBIND ]
then
  printf "\tnew_ip_address:%s\n" "${new_ip_address:?}"
fi

exit 0;
